services:
  profilarr:
      image: python:3.12-slim-bullseye
      container_name: profilarr
      command: >
            bash -c "
            apt-get update &&
            apt-get -y install git &&
            mkdir /app &&
            cd /app &&
            echo cloning repo - $${GIT_REPO} int /app &&
            git clone $${GIT_REPO} /app &&
            echo Installing PIP &&
            pip install -r /app/requirements.txt &&
            sleep 10 &&
            echo Running Setup &&
            python /app/setup.py &&
            echo Done - Ready to interact. &&
            tail -f /dev/null"   
      environment:
        - GIT_REPO=https://github.com/santiagosayshey/Profilarr.git
        - MASTER_RADARR_BASEURL=http://hostname:7878 #replace with your actual servername
        - MASTER_RADARR_APIKEY=ABCEasdffgsrtye54y45y54 #replace with your actual API Key
        - MASTER_SONARR_BASEURL=http://hostname:8989 #replace with your actual servername
        - MASTER_SONARR_APIKEY=ABCEasdffgsrtye54y45y54 #replace with your actual API Key
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
      networks:
        - backend
      restart: no
      stdin_open: true 
      tty: true
