version: "3.3"

x-common-settings: &common-settings
  environment:
    PUID: 0 # user id, change as necessary
    PGID: 0 # group id, change as necessary
    TZ: Europe/London # timezone, change as necessary
  restart: unless-stopped

services:
  radarr:
    <<: *common-settings
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7887:7878" # change the left value to the desired host port for Radarr
    volumes:
      - radarr_movies:/movies

  radarr2:
    <<: *common-settings
    image: linuxserver/radarr
    container_name: radarr2
    ports:
      - "7888:7878" # change the left value to the desired host port for Radarr

  sonarr:
    <<: *common-settings
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8998:8989" # change the left value to the desired host port for Sonarr

  sonarr2:
    <<: *common-settings
    image: linuxserver/sonarr
    container_name: sonarr2
    ports:
      - "8999:8989" # change the left value to the desired host port for Sonarr

volumes:
  radarr_movies: # Docker managed volume for movies
