name: Run Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run regex tests
        run: python ./tests/regex.py

    # Add more test jobs for other types of tests
    # - name: Run other tests
    #   run: python ./tests/other_tests.py
